/* tslint:disable */
/* eslint-disable */

/**
 * OAI-Secure access token.
 */
export interface AccessToken {

  /**
   * Access token generated by the Cumulocity IoT platform.
   */
  access_token?: string;
}
