/* tslint:disable */
/* eslint-disable */

/**
 * Statistics file metadata.
 */
export interface StatisticsFile {

  /**
   * Start date or date and time of the statistics attached in the file.
   */
  dateFrom?: string;

  /**
   * End date or date and time of the statistics attached in the file.
   */
  dateTo?: string;

  /**
   * File generation date.
   */
  generationDate?: string;

  /**
   * Unique identifier of the file.
   */
  id?: string;

  /**
   * Domain name where the statistics file come from.
   */
  instanceName?: string;

  /**
   * The type of statistics:
   * * REAL - generated by the system on the first day of the month and including statistics from the previous month.
   * * TEST - generated by the user with a time range specified in the query parameters (`dateFrom`, `dateTo`).
   */
  type?: 'REAL' | 'TEST';
}
